server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: '*'

turbine:
  app-config: 'ribbon-consumer'
  combine-host-port: true

spring:
  application:
    name: 'ribbon-consumer'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:1111/eureka/'