server:
  port: 8080

spring:
  application:
    name: 'demo-app'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true